<a href="https://colab.research.google.com/github/rosh4nn/ML-IrisDataset-project1/blob/main/IrisData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/IRIS.csv')
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [ ]:
df.shape

(150, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.054000,3.758667,1.198667
std,0.828066,0.433594,1.764420,0.763161
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [ ]:
df[df.duplicated()]

,sepal_length,sepal_width,petal_length,petal_width,species
34,4.9,3.1,1.5,0.1,Iris-setosa
37,4.9,3.1,1.5,0.1,Iris-setosa
142,5.8,2.7,5.1,1.9,Iris-virginica


In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df[df.duplicated()]

,sepal_length,sepal_width,petal_length,petal_width,species


In [ ]:
df.isna().sum()

,0
sepal_length,0
sepal_width,0
petal_length,0
petal_width,0
species,0


In [ ]:
x = df.iloc[:,:-1]
x

,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [ ]:
y = df.iloc[:,-1]
y

,species
0,Iris-setosa
1,Iris-setosa
2,Iris-setosa
3,Iris-setosa
4,Iris-setosa
...,...
145,Iris-virginica
146,Iris-virginica
147,Iris-virginica
148,Iris-virginica


In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train

,sepal_length,sepal_width,petal_length,petal_width
127,6.1,3.0,4.9,1.8
134,6.1,2.6,5.6,1.4
44,5.1,3.8,1.9,0.4
140,6.7,3.1,5.6,2.4
28,5.2,3.4,1.4,0.2
...,...,...,...,...
135,7.7,3.0,6.1,2.3
139,6.9,3.1,5.4,2.1
74,6.4,2.9,4.3,1.3
143,6.8,3.2,5.9,2.3


In [ ]:
x_test

,sepal_length,sepal_width,petal_length,petal_width
101,5.8,2.7,5.1,1.9
95,5.7,3.0,4.2,1.2
56,6.3,3.3,4.7,1.6
105,7.6,3.0,6.6,2.1
100,6.3,3.3,6.0,2.5
77,6.7,3.0,5.0,1.7
91,6.1,3.0,4.6,1.4
55,5.7,2.8,4.5,1.3
46,5.1,3.8,1.6,0.2
61,5.9,3.0,4.2,1.5


In [ ]:
y_train

,species
127,Iris-virginica
134,Iris-virginica
44,Iris-setosa
140,Iris-virginica
28,Iris-setosa
...,...
135,Iris-virginica
139,Iris-virginica
74,Iris-versicolor
143,Iris-virginica


In [ ]:
y_test

,species
101,Iris-virginica
95,Iris-versicolor
56,Iris-versicolor
105,Iris-virginica
100,Iris-virginica
77,Iris-versicolor
91,Iris-versicolor
55,Iris-versicolor
46,Iris-setosa
61,Iris-versicolor


In [ ]:
y_train.value_counts()

,count
species,
Iris-virginica,41
Iris-setosa,39
Iris-versicolor,37


In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
x_train1,y_train1 = smote.fit_resample(x_train,y_train)

In [ ]:
y_train1.value_counts()

,count
species,
Iris-virginica,41
Iris-setosa,41
Iris-versicolor,41


In [ ]:
# feature Scaling Using StandardScaler

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train1 = sc.fit_transform(x_train1)
x_train1

array([[ 3.62720003e-01, -1.13177013e-01,  6.68996930e-01,
         7.97624436e-01],
       [ 3.62720003e-01, -1.13257550e+00,  1.07101368e+00,
         2.70677454e-01],
       [-8.45774206e-01,  1.92561996e+00, -1.05393202e+00,
        -1.04669000e+00],
       [ 1.08781653e+00,  1.41672609e-01,  1.07101368e+00,
         1.58804491e+00],
       [-7.24924785e-01,  9.06221475e-01, -1.34108684e+00,
        -1.31016349e+00],
       [-1.69172015e+00,  3.96522231e-01, -1.39851781e+00,
        -1.31016349e+00],
       [ 1.81291305e+00, -3.68026635e-01,  1.47303044e+00,
         7.97624436e-01],
       [ 1.32951537e+00,  3.96522231e-01,  1.12844465e+00,
         1.45630816e+00],
       [-8.45774206e-01,  1.16107110e+00, -1.34108684e+00,
        -1.17842675e+00],
       [-1.20677681e-01, -1.38742512e+00,  7.26427895e-01,
         1.06109793e+00],
       [-3.62376523e-01, -1.64227474e+00,  3.72563157e-02,
        -1.24532783e-01],
       [ 3.62720003e-01, -6.22876257e-01,  1.52118246e-01,
      

In [ ]:
x_test = sc.transform(x_test)
x_test

array([[ 1.71740112e-04, -8.77725879e-01,  7.83858860e-01,
         9.29361182e-01],
       [-1.20677681e-01, -1.13177013e-01,  2.66980175e-01,
         7.20396281e-03],
       [ 6.04418844e-01,  6.51371853e-01,  5.54135000e-01,
         5.34150945e-01],
       [ 2.17546132e+00, -1.13177013e-01,  1.64532333e+00,
         1.19283467e+00],
       [ 6.04418844e-01,  6.51371853e-01,  1.30073754e+00,
         1.71978166e+00],
       [ 1.08781653e+00, -1.13177013e-01,  7.26427895e-01,
         6.65887691e-01],
       [ 3.62720003e-01, -1.13177013e-01,  4.96704035e-01,
         2.70677454e-01],
       [-1.20677681e-01, -6.22876257e-01,  4.39273070e-01,
         1.38940708e-01],
       [-8.45774206e-01,  1.92561996e+00, -1.22622491e+00,
        -1.31016349e+00],
       [ 1.21021161e-01, -1.13177013e-01,  2.66980175e-01,
         4.02414200e-01],
       [-4.83225943e-01,  2.18046958e+00, -1.16879395e+00,
        -1.04669000e+00],
       [-4.83225943e-01,  2.18046958e+00, -1.39851781e+00,
      

In [ ]:
# from sklearn.neighbors import KNeighborsClassifier

# knn = KNeighborsClassifier(n_neighbors=7)
# knn

In [ ]:
# knn.fit(x_train1,y_train1)

In [ ]:
# y_pred = knn.predict(x_test)
# y_pred

In [ ]:
from sklearn.svm import SVC

svm = SVC(C=1,kernel='poly')
svm

SVC(C=1, kernel='poly')

In [ ]:
svm.fit(x_train1,y_train1)

SVC(C=1, kernel='poly')

In [ ]:
y_pred = svm.predict(x_test)
y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica'],
      dtype=object)

In [ ]:
# performance evaluation
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm = confusion_matrix(y_test,y_pred)
print(cm)

accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

cr = classification_report(y_test,y_pred)
print(cr)

[[ 9  0  0]
 [ 0 13  0]
 [ 0  0  8]]
1.0
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

